"""initial schema: listings, canonical_items, listing_matches, unmatched_listings

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-11

Hand-written to match db/models.py exactly, rather than autogenerated --
there's no live Postgres in the environment this was written in to
autogenerate against. Run `alembic upgrade head` against a real database
(e.g. via docker-compose) and confirm before trusting this blindly; future
schema changes can go back to the normal `alembic revision --autogenerate`
flow against a running db.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("brand", sa.String(length=150), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("size", sa.String(length=50), nullable=True),
        sa.Column("condition", sa.String(length=150), nullable=True),
        sa.Column("seller_rating", sa.Float(), nullable=True),
        sa.Column("photo_count", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("source", "external_id", name="uq_listings_source_external_id"),
    )

    op.create_table(
        "canonical_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("brand", sa.String(length=150), nullable=False),
        sa.Column("line_or_era", sa.String(length=100), nullable=True),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
    )

    op.create_table(
        "listing_matches",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "listing_id",
            sa.Integer(),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "canonical_item_id",
            sa.Integer(),
            sa.ForeignKey("canonical_items.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_listing_matches_canonical_item_id", "listing_matches", ["canonical_item_id"]
    )

    op.create_table(
        "unmatched_listings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "listing_id",
            sa.Integer(),
            sa.ForeignKey("listings.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("raw_title", sa.Text(), nullable=False),
        sa.Column("best_score", sa.Float(), nullable=True),
        sa.Column(
            "best_candidate_id",
            sa.Integer(),
            sa.ForeignKey("canonical_items.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("unmatched_listings")
    op.drop_index("ix_listing_matches_canonical_item_id", table_name="listing_matches")
    op.drop_table("listing_matches")
    op.drop_table("canonical_items")
    op.drop_table("listings")
